### ISSUE TITLE
Add support for simple logging

### ISSUE THREAD

**Issue by danbst** [tmiasko/arbtt-capture#1]
Without arbtt-import, just post JSON entried to a log file. One can then setup logrotate with compression, and run analysis not with arbtt.

I don't know other gnome shell extensions which can do that.

**Comment by tmiasko** [comment]
Sounds reasonable if someone would like to contribute this. Though, if you are
not really interested in integration with arbtt, it seems that it might be
better idea to create a separate extension with full control over what
information is logged, in what format, and where.

BTW, it is already possible, if you go through the effort of creating custom
data importer, and configuring it as arbtt-import command with different log
path (to avoid corrupting existing data). For example:

```python
#!/usr/bin/env python3
import argparse
import sys

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Process some integers.')
    parser.add_argument('--append', action='store_true')
    parser.add_argument('--format', type=str)
    parser.add_argument('--logfile', type=str, required=True)
    args = parser.parse_args()
    
    with open(args.logfile, 'a') as file:
        for line in sys.stdin:
            file.write(line)
            file.flush()
```

**Comment by danbst** [comment]
@tmiasko I'd prefer to use existing extension, because there is higher chance it will be supported between different Gnome versions. Until now arbtt-capture was broken for me on gnome 3.30.2
```
[arbtt-capture] Error while writing log entry, stopping writer: global.screen is undefined
                                                  Stack trace:
                                                  generateLogEntry@/home/danbst/.local/share/gnome-shell/extensions/arbtt-capture@tmiasko.github.com/extension.js:115:15
                                                  startWriter/this._timeoutId<@/home/danbst/.local/share/gnome-shell/extensions/arbtt-capture@tmiasko.github.com/extensi>
```
But you've released a fix, much thanks! Maintaining own extension would be a nightmare for me.

I've patched your extension to use `tee` as an importer, but I'll try your suggestion. It looks cleaner.

**Comment by danbst** [comment]
@tmiasko yup, your suggested custom importer works! Maybe add a small note about it in readme?

As my request is fulfilled, closing issue.
